version: '3.8'
services:
  web:
    image: 401657292421.dkr.ecr.us-east-1.amazonaws.com/film-recipes/api:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always