name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 401657292421.dkr.ecr.us-east-1.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Build and Push Image
        run: |
          docker build -t film-recipes-api:latest .
          docker tag film-recipes-api:latest 401657292421.dkr.ecr.us-east-1.amazonaws.com/film-recipes/api:latest
          docker push 401657292421.dkr.ecr.us-east-1.amazonaws.com/film-recipes/api:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # The public IP address of the EC2 instance
          username: ubuntu
          key: ${{ secrets.EC2_KEY }} # The private key to connect to the EC2 instance
          script: |
            cd /home/ubuntu/app

            # Create or update the .env file with secrets
            echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
            echo "ALGORITHM=${{ secrets.ALGORITHM }}" >> .env
            echo "ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}" >> .env

            # Log in to ECR on EC2 instance using IAM role credentials
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 401657292421.dkr.ecr.us-east-1.amazonaws.com

            # Remove old images
            docker image prune -a -f

            # Pull the latest image from ECR
            docker compose pull

            # Restart the containers with the updated image
            docker compose up -d --force-recreate

            # Optional: Remove unused images to save space
            docker image prune -f

            # Optional: Run database migrations if applicable
            # docker-compose run web alembic upgrade head

      - name: Run Database Migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # The public IP address of the EC2 instance
          username: ubuntu
          key: ${{ secrets.EC2_KEY }} # The private key to connect to the EC2 instance
          script: |
            cd /home/ubuntu/app
            docker compose run web alembic upgrade head